# Generated by Django 3.0.7 on 2020-06-27 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_addtocart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddToCart',
            new_name='ProductSelected',
        ),
    ]
